[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
itertools = "0.10.5"
logos = "0.12.1"
once_cell = "1.16.0"
regex = "1.7.0"
slotmap = "1.0.6"
thiserror = "1.0.37"

